### ISSUE TITLE
lab-gui-930

### ISSUE THREAD

**Issue by amcar-dtu** [dtudk/Admin#1]
**Lab GUI 930**

MATLAB-based GUI for our optical setup in Lab 930.

**License**

For the moment we need a **private** project in order to keep it internally.

**Maintainer User**

- amcar@dtu.dk
- mofis@dtu.dk

**SNF**

**Associated Data**

**Comment by amcar-dtu** [comment]
@zerothi @nicpa-dtu are you in charge of this operations? who should I ask to in order to get the repo created? Thanks for your help

**Comment by zerothi** [comment]
First a small note.
1) we do not have a license agreement with Github, this means that we are using the Free Github version. You will _NOT_ be able to be more than 3 collaborators on the project. We will also not be able to manage more permissions than this being a private repo, as such it might be a bit difficult for you to allow PR's etc.
2) As per instructions by the legal department we are not allowed to make this project public due to the SNF requirements (as it stands). We hope that in the near future this issue may be partially resolved, one way or another.

If you think your project still applies to this I will do this next week! :)

Thanks!

**Comment by amcar-dtu** [comment]
hi @zerothi thanks for your answer. For us is perfect to have it private. Regarding the number of collaborators, by *collaborators* you mean `developer` role or any profile that can have access?

**Comment by zerothi** [comment]
> ... Regarding the number of collaborators, by _collaborators_ you mean `developer` role or any profile that can have access?

Yes.

**Comment by amcar-dtu** [comment]
So in synthesis we can create only `private` repos and only 3 of us can clone that repo and push to it?

**Comment by zerothi** [comment]
Yes, the # 3 is limited by the free access we have, and the public repo is currently limited by the legal department.

**Comment by amcar-dtu** [comment]
ok still would be useful to have our repo under a common DTU space and not on our personal (still DTU email related) account so if you are ok I will go with that. Thanks a lot

**Comment by zerothi** [comment]
I have created your repository.

I have also created a team for you.

As this is the first project hosted here, expect some hickups, we all need to learn how to handle this in a broader sense ;)
I hope you will be happy with the way this will work until we get some more loose accessibility. :)

**Comment by zerothi** [comment]
There are still a set of limititations:
- no github actions (since the restrictions apply to the entire organization)
- you will not be able to change visibility of the project (contact `dtudk-admin` team for help)
- you will not be able to delete the project (contact `dtudk-admin` team for help.

**Comment by amcar-dtu** [comment]
hi @zerothi thanks a lot! now I see the repo, the DTU Organization and the team.
Couple of questions:
- I don't see any `maintainer` for [lab-gui-930 team](https://github.com/orgs/dtudk/teams/lab-gui-930/members): is there any? can it be one of us?
- could be possible to change the [lab-gui-930 team](https://github.com/orgs/dtudk/teams/lab-gui-930) name to `Nicolas Group`?
- I'm not able to see any `maintainer` for [lab-gui-930 repo](https://github.com/dtudk/lab-gui-930/): who's that role?

Thanks a lot for all your help!

**Comment by zerothi** [comment]
> hi @zerothi thanks a lot! now I see the repo, the DTU Organization and the team. Couple of questions:
> 
>     * I don't see any `maintainer` for [lab-gui-930 team](https://github.com/orgs/dtudk/teams/lab-gui-930/members): is there any? can it be one of us?

Currently both of you are in the `lab-gui-930 team` which has the "maintain" permissions set. So you should both be able to push to the repo, in case this is not working, let me know!

Since you have a private repo with no license attached, I will have to not allow you to be *admin*. An admin may change the private/public attribute, and we are not allowed (by legal) to have public repo's without licenses + SNF; at the moment!

> 
>     * could be possible to change the [lab-gui-930 team](https://github.com/orgs/dtudk/teams/lab-gui-930) name to `Nicolas Group`?

I would prefer that the teams reflect the repositories that they control, there might be several others named "Nicolas" at DTU (I can at least think of 1 right of the bat). In case you want several repo's under a given team's control, we might figure out a name according to `<institute>-<section>` if that helps?  
This limitation is mainly for maintenance reasons, in the long run ;)
 
>     * I'm not able to see any `maintainer` for [lab-gui-930 repo](https://github.com/dtudk/lab-gui-930/): who's that role?

As mentioned above, the team has the "maintain" attribute, so I hope/think you both should have that attribute. Let me know if there are any problems!

> 
> Thanks a lot for all your help!

**Comment by amcar-dtu** [comment]
hi @zerothi thanks a lot for all the explanations, I'm fine with all of them. At this point I would just like to have a name for the team more related to our department/research group, since we are planning to upload other repos for our group in the next future.
If it may help, we are the 2D Materials Group of the Fotonik/Elektro department, so according to your convention the name could be `elektro-nanofotonik-2dmat`. Let me know if you find it ok 😄

**Comment by zerothi** [comment]
Ok, sounds fine.
I will do this then:

1. Create a parent team `elektro-nanofotonik-2dmat` team
2. make the `lab-gui-930` team a child of the above. In this way the parent team can more easily control stuff :)
Would this be ok?

**Comment by amcar-dtu** [comment]
ok great, makes sense! thanks a lot 😁

**Comment by zerothi** [comment]
Great, I will close this issue as resolved, I will also add the same two emails to the new team, if you want additional members to that team, please open up a new issue!

**Comment by amcar-dtu** [comment]
hi @zerothi, we need to add another member of our group to this repo, so to the [electro-nanofotonik-2dmat](https://github.com/orgs/dtudk/teams/electro-nanofotonik-2dmat) team and to the [lab-gui-930](https://github.com/orgs/dtudk/teams/lab-gui-930). Could you please help us on that? Best, Amedeo

**Comment by zerothi** [comment]
Username?

**Comment by amcar-dtu** [comment]
hi @zerothi sorry my bad, the username is @Cornekoks. Thanks a lot!

**Comment by zerothi** [comment]
done.

**Comment by zerothi** [comment]
Well, the user needs to accept? I can't do that for the user!

**Comment by Cornekoks** [comment]
I'm in, thanks a lot!

**Comment by amcar-dtu** [comment]
you are right, we solve in the end :) thanks a lot!
